image: lholota/bash-git

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - bash -e ./tools/gitsync.sh pack
    - bash -e ./tools/gitsync.sh deploy mbfiles ${CI_COMMIT_REF_NAME} ${GL_REF}/monlor/mbfiles.git
