image: lholota/bash-git:latest

stages:
  - pack
  - deploy

pack:
  stage: pack
  only:        
    - master
    - test
    - dev
  script:
    - bash -e ./tools/gitsync.sh pack
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths: 
      - mbfiles/

deploy-gitlab:
  stage: deploy
  only:        
    - master
    - test
    - dev
  script:
    - bash -e ./tools/gitsync.sh deploy mbfiles ${CI_COMMIT_REF_NAME} ${GL_REF}/monlor/mbfiles.git
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths: 
      - mbfiles/

deploy-coding:
  stage: deploy
  only:        
    - master
    - test
  script:
    - bash -e ./tools/gitsync.sh deploy mbfiles ${CI_COMMIT_REF_NAME} ${CO_REF}/monlor/mbfiles.git
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths: 
      - mbfiles/

pack-master:
  stage: pack
  only:
    - tags
  tags:
    - deploy-*
  script:
    - git fetch origin master
    - git checkout master
    - bash -e ./tools/gitsync.sh pack mbfiles-master
  cache:
    key: deploy-master
    paths: 
      - mbfiles-master/

pack-test:
  stage: pack
  only:
    - tags
  tags:
    - deploy-*
  script:
    - git fetch origin test
    - git checkout test
    - bash -e ./tools/gitsync.sh pack mbfiles-test
  cache:
    key: deploy-test
    paths:
      - mbfiles-test/

deploy-master:
  stage: deploy
  only:
    - tags
  tags:
    - deploy-*
  script:
    - bash -e ./tools/gitsync.sh deploy mbfiles-master ${CI_COMMIT_REF_NAME} ${CO_REF}/monlor/mbfiles.git
  cache:
    key: deploy-master
    paths: 
      - mbfiles-master/

deploy-test:
  stage: deploy
  only:
    - tags
  tags:
    - deploy-*
  script:
    - bash -e ./tools/gitsync.sh deploy mbfiles-test ${CI_COMMIT_REF_NAME} ${CO_REF}/monlor/mbfiles.git
  cache:
    key: deploy-test
    paths:
      - mbfiles-test/



