image: lholota/bash-git:latest

stages:
  - pack
  - deploy
  - syncode

pack:branchs:
  stage: pack
  only:        
    - master
    - test
    - dev
  script:
    - bash -e ./tools/gitsync.sh pack
  retry: 2
  cache:
    key: ${CI_COMMIT_REF_NAME}
    untracked: true

deploy:branchs:
  stage: deploy
  only:        
    - master
    - test
  script:
    - apk add git-lfs
    - bash ./tools/gitsync.sh deploy mbfiles ${CI_COMMIT_REF_NAME} ${GL_REF}/monlor/mbfiles.git
    - bash ./tools/gitsync.sh deploy mbfiles ${CI_COMMIT_REF_NAME} ${CO_REF}/monlor/mbfiles.git
    - bash ./tools/gitsync.sh deploy mbfiles ${CI_COMMIT_REF_NAME} ${GH_REF}/monlor/mbfiles.git
  cache:
    key: ${CI_COMMIT_REF_NAME}
    untracked: true

deploy:dev:
  stage: deploy
  only:        
    - dev
  script:
    - apk add git-lfs
    - bash ./tools/gitsync.sh deploy mbfiles ${CI_COMMIT_REF_NAME} ${GL_REF}/monlor/mbfiles.git
  cache:
    key: ${CI_COMMIT_REF_NAME}
    untracked: true

pack:master:
  stage: pack
  only:
    - tags
  tags:
    - deploy-*
  script:
    - git fetch origin master
    - git checkout master
    - bash -e ./tools/gitsync.sh pack
  retry: 2
  # artifacts:
  #   paths:
  #   - mbfiles-msater/
  cache:
    key: master
    untracked: true

pack:test:
  stage: pack
  only:
    - tags
  tags:
    - deploy-*
  script:
    - git fetch origin test
    - git checkout test
    - bash -e ./tools/gitsync.sh pack
  retry: 2
  # artifacts:
  #   paths:
  #   - mbfiles-test/
  cache:
    key: test
    untracked: true

deploy:master:
  stage: deploy
  only:
    - tags
  tags:
    - deploy-*
  script:
    - apk add git-lfs
    - bash ./tools/gitsync.sh deploy mbfiles master ${CO_REF}/monlor/mbfiles.git
  # dependencies:
  #   - pack:master
  #   - pack:test
  cache:
    key: master
    untracked: true

deploy:test:
  stage: deploy
  only:
    - tags
  tags:
    - deploy-*
  script:
    - apk add git-lfs
    - bash ./tools/gitsync.sh deploy mbfiles test ${CO_REF}/monlor/mbfiles.git
  # dependencies:
  #   - pack:master
  #   - pack:test
  cache:
    key: test
    untracked: true

syncode:github:
  stage: syncode
  only:        
    - master
    - test
    - dev
  script:
    - git fetch origin ${CI_COMMIT_REF_NAME}
    - git checkout ${CI_COMMIT_REF_NAME}
    - git push ${GH_REF}/monlor/MIXBOX.git ${CI_COMMIT_REF_NAME}:${CI_COMMIT_REF_NAME}

# cache:
#   key: ${CI_COMMIT_REF_NAME}
#   untracked: true
#   paths: 
#     - mbfiles/

