name: Dev-CI

# on: [push, pull_request]
on: 
  push:
    branchs:  
      - dev
    ignore-paths:
      - '.github'
      - 'README.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        GL_TOKEN: ${{ secrets.GL_TOKEN }}
        GL_URL: ${{ secrets.GL_URL }}
        BRANCH_NAME: dev
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Pack And Deploy
      run: |
        bash ./tools/gitsync.sh pack 
        bash ./tools/gitsync.sh deploy mbfiles ${BRANCH_NAME} http://${GL_TOKEN}@${GL_URL}/monlor/mbfiles.git

    - name: Sync Code
      run: git push http://${GL_TOKEN}@${GL_URL}/monlor/mixbox.git ${BRANCH_NAME}:${BRANCH_NAME}
