name: Main-CI

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        GH_REF: ${{ secrets.GH_REF }}
        CO_REF: ${{ secrets.CO_REF }}
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Pack And Deploy
      run: |
        bash ./tools/gitsync.sh pack 
        bash ./tools/gitsync.sh deploy mbfiles `git branch | awk  '$1 == "*"{print $2}'` ${GH_REF}
        bash ./tools/gitsync.sh deploy mbfiles `git branch | awk  '$1 == "*"{print $2}'` ${CO_REF}
