name: CI

# on:
#   push:
#     branchs:
#       - 'test'
#       - 'master'
#   pull_request:
#     branchs:
#       - 'test'
#       - 'master'
    # paths: 
    #   - 'apps/**'
    #   - 'appsbin/**'
    #   - 'temp/**'
# on: [push, pull_request] 
on: 
    push:
        paths-ignore:
            - 'README.md'
            - 'tools'
            - '.github'
        branchs:
            - 'test'
            - 'master'
    pull_request:
        paths-ignore:
            - 'README.md'
            - 'tools'
            - '.github'
        branchs:
            - 'test'
            - 'master'        

jobs:
  publish:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Pack files
      run: |
        git lfs pull
        mkdir appstore/
        mkdir mbfiles/
        bash ./tools/gitsync.sh pack all
        cp -rf appsbin/ mbfiles/appsbin/
        cp -rf appstore/ mbfiles/appstore/
        cp -rf temp/ mbfiles/temp/
        cp -rf applist.txt mbfiles/
        cp -rf install.sh mbfiles/
    - name: Push changes
      env:
        GH_REF: github.com/monlor/mbfiles
        GE_REF: gitee.com/monlor/mbfiles
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GE_TOKEN: ${{ secrets.GE_TOKEN }}
        BRANCH_NAME: $(cd .. && git branch | awk  '$1 == "*"{print $2}')
      run: |
        cd mbfiles/
        git init
        git config --local user.email "monlor@qq.com"
        git config --local user.name "monlor"
        git add .
        git commit -m "$(TZ='Asia/Shanghai' date "+%Y-%m-%d %H:%M:%S")" -a
        eval "git branch | grep -q "${BRANCH_NAME}" || git checkout -b "${BRANCH_NAME}""
        eval "git push "https://${GH_TOKEN}@${GH_REF}" "${BRANCH_NAME}":"${BRANCH_NAME}" -f"
        echo "${GE_TOKEN}" > /root/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        eval "git push "https://${GE_REF}" "${BRANCH_NAME}":"${BRANCH_NAME}" -f"
