name: Main-CI

# on: [push, pull_request]
on: 
  push:
    branchs:  
      - master
      - test
      - dev
    paths-ignore:
      - '.github/**'
      - 'README.md'
  # pull_request:
  #   branchs:  
  #     - master
  #     - test
  #     - dev

jobs:
  coding-deploy:
    runs-on: ubuntu-latest
    env:
        CO_REF: ${{ secrets.CO_REF }}
        BRANCH_NAME: ${{ github.ref }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy To Coding
      run: |
        git clone -b `basename ${BRANCH_NAME}` ${CO_REF}
        bash ./tools/gitsync.sh pack 
        bash ./tools/gitsync.sh deploy_lfs mbfiles `basename ${BRANCH_NAME}` ${CO_REF}

  github-deploy:
    runs-on: ubuntu-latest
    env:
        GH_REF: ${{ secrets.GH_REF }}
        BRANCH_NAME: ${{ github.ref }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy To GitHub
      run: |
        git clone -b `basename ${BRANCH_NAME}` ${GH_REF}
        bash ./tools/gitsync.sh pack 
        bash ./tools/gitsync.sh deploy mbfiles `basename ${BRANCH_NAME}` ${GH_REF}