name: Master-CI

on: 
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - 'master1'
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - 'master1'        

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Pack files
      run: |
        mkdir appstore/
        mkdir mbfiles/
        bash ./tools/gitsync.sh pack all
        cp -rf appsbin/ mbfiles/appsbin/
        cp -rf appstore/ mbfiles/appstore/
        cp -rf temp/ mbfiles/temp/
        cp -rf applist.txt mbfiles/
        cp -rf install.sh mbfiles/

    - name: Push to Github
      env:
        GH_REF: github.com/monlor/mbfiles
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd mbfiles/
        git init
        git config --local user.email "monlor@qq.com"
        git config --local user.name "monlor"
        git add .
        git commit -m "$(TZ='Asia/Shanghai' date "+%Y-%m-%d %H:%M:%S")" -a
        git push "https://${GH_TOKEN}@${GH_REF}" master:master -f

    - name: Push to Gitee
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: git@gitee.com:monlor/mbfiles.git
        BRANCH: master
        FOLDER: mbfiles
        SSH_PRIVATE_KEY: ${{ secrets.GE_TOKEN }}
        KNOWN_HOSTS_FILE: temp/known_hosts # Needed if target repo is not on github.com

      
