name: Tag-CI

on: 
  push:
    tags:  
      - deploy-*

env:
  GH_REF: ${{ secrets.GH_REF }}
  CO_REF: ${{ secrets.CO_REF }}

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Pack And Deploy
      env:
        BRANCH_NAME: master
      run: |
        git checkout ${BRANCH_NAME}
        bash ./tools/gitsync.sh pack 
        bash -x ./tools/gitsync.sh deploy mbfiles ${BRANCH_NAME} ${GH_REF}
        bash -x ./tools/gitsync.sh deploy mbfiles ${BRANCH_NAME} ${CO_REF}

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Pack And Deploy
      env:
        BRANCH_NAME: test
      run: |
        git checkout ${BRANCH_NAME}
        bash ./tools/gitsync.sh pack 
        bash -x ./tools/gitsync.sh deploy mbfiles ${BRANCH_NAME} ${GH_REF}
        bash -x ./tools/gitsync.sh deploy mbfiles ${BRANCH_NAME} ${CO_REF}

  dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Pack And Deploy
      env:
        BRANCH_NAME: dev
      run: |
        git checkout ${BRANCH_NAME}
        bash ./tools/gitsync.sh pack 
        bash -x ./tools/gitsync.sh deploy mbfiles ${BRANCH_NAME} ${GH_REF}
        bash -x ./tools/gitsync.sh deploy mbfiles ${BRANCH_NAME} ${CO_REF}
